### PR TITLE
OS-8338 lx_nfs structures declare variables

### PR DESCRIPTION
**Pull request by danmcd**
Test notes are in the ticket.

### CODE REVIEW

**Review by papertigers — APPROVED** [review]

**Comment by citrus-it** [comment]
LGTM - I wonder why I haven't seen this crop up in the gcc 10 builds on OmniOS - it looks like the same code is there.

**Comment by danmcd** [comment]
> LGTM - I wonder why I haven't seen this crop up in the gcc 10 builds on OmniOS - it looks like the same code is there.

Do you suppress warnings in lx that maybe we don't in ours?

**Comment by citrus-it** [comment]
> > LGTM - I wonder why I haven't seen this crop up in the gcc 10 builds on OmniOS - it looks like the same code is there.
> 
> Do you suppress warnings in lx that maybe we don't in ours?

Sorry, we have a fix from May https://github.com/citrus-it/illumos-omnios/commit/5d1d25622be5aad1002be1774e276d8662295f2f

At least we agree!

**Review by bahamat — APPROVED** [review]

**Comment by bahamat** [comment]
```
 \++================================|                    _=_
  \_________________________________/              ___/==+++==\___
               """\__      \"""       |======================================/
                     \__    \_          / ..  . _/--===+_____+===--""
                        \__   \       _/.  .. _/         `+'
                           \__ \   __/_______/
                          ___-\_\-'---==+____|
                    __--+" .    . .        "==_
                    /  |. .  ..     -------- | \
                    "==+_    .   .  -------- | /
                         ""\___  . ..     __=="
                               """"--=--""
                                                           Ship it!
```

**Pull request merged**
