### PR TITLE
OS-8158 Support NVMe as device model for bhyve

### PR DESCRIPTION
**Pull request by sjorge**
smartos-live counterpart: joyent/smartos-live#924

# TODO
- [X] change bhyve brand boot.c
- [x] vmadm props update
  - [x] update manpage to mention windows 10 guests only
- [x] update vmadm man page (smartos-live)
- [x] collect test results / build pi (takes like 4h)
  - [x] windows vm
  - [x] freebsd vm
  - [x] omnios vm
  - [x] /usr/vm/test/runtests

# Motivation
While testing a newer firmware from one of the freebsd developers that should have working vnc, ppt and nvme on latest ed2k firmware... I noticed I could not test the nvme bit on SmartOS.

OmniOS already supports it and via bhyve_extra_opts I was able to add a nvme disk. The work to expose this within SmartOS is not to complicated, I did the work to add ahci support in the past so it is within my skill level to do so.

### CODE REVIEW

**Comment by sjorge** [comment]
:| I'm very confused... my change seems to cause:

```
/usr/kernel/brand/amd64/lx_brand: undefined symbol 'sprunprlock'
WARNING: mod_load: cannot load module 'lx_brand'
/usr/kernel/drv/amd64/lx_systrace: undefined symbol 'lx_sysent64'
/usr/kernel/drv/amd64/lx_systrace: undefined symbol 'lx_sysent32'
/usr/kernel/drv/amd64/lx_systrace: undefined symbol 'lx_brand_systrace_disable'
/usr/kernel/drv/amd64/lx_systrace: undefined symbol 'lx_nsysent64'
/usr/kernel/drv/amd64/lx_systrace: undefined symbol 'lx_nsysent32'
/usr/kernel/drv/amd64/lx_systrace: undefined symbol 'lx_systrace_entry_ptr'
/usr/kernel/drv/amd64/lx_systrace: undefined symbol 'lx_systrace_return_ptr'
/usr/kernel/drv/amd64/lx_systrace: undefined symbol 'lx_brand_systrace_enable'
WARNING: mod_load: cannot load module 'lx_systrace'
WARNING: lx_systrace: unable to resolve dependency, module 'brand/lx_brand' not found
```

I reverted to a clean build from master and the error is gone, rebuild with my change to boot.c and this is back? I haven't touched lx at all.

**Comment by sjorge** [comment]
Seems to get it on master also now, did a fresh build without my changes.

**Comment by jasonbking** [comment]
I think this morning's illumos-gate merge caused that -- I don't believe it's anything you caused. Hopefully we'll have it fixed here in a bit.

**Comment by sjorge** [comment]
> I think this morning's illumos-gate merge caused that -- I don't believe it's anything you caused. Hopefully we'll have it fixed here in a bit.

Ack, just saw #289 so will do another build after that gets merged.

**Comment by sjorge** [comment]
Rebased on master and building a new PI

**Comment by sjorge** [comment]
Functional testing:

Adding a nvme disk:
```
[root@boron ~]# echo '{"add_disks": [{"size": 1024, "model": "nvme"}]}' | vmadm update eceec5eb-22c7-e65b-fd6b-81ebdb36406b
Successfully updated VM eceec5eb-22c7-e65b-fd6b-81ebdb36406b
```

It no longer complains about nvme being unsupported (pre changes):
```
[root@boron ~]# echo '{"add_disks": [{"size": 1024, "model": "nvme"}]}' | vmadm update eceec5eb-22c7-e65b-fd6b-81ebdb36406b
"nvme" is not a valid disk model for bhyve brand. Valid are: virtio,ahci
```

Running pargs against the bhyve process to verify the command gets passed correctly:
```
[root@boron ~]# pargs 7125
7125:   bhyve -H -U eceec5eb-22c7-e65b-fd6b-81ebdb36406b -B 1,manufacturer=Joyent,produ
argv[0]: bhyve
argv[1]: -H
argv[2]: -U
argv[3]: eceec5eb-22c7-e65b-fd6b-81ebdb36406b
argv[4]: -B
argv[5]: 1,manufacturer=Joyent,product=SmartDC HVM,version=7.20200410T143307Z,serial=eceec5eb-22c7-e65b-fd6b-81ebdb36406b,sku=001,family=Virtual Machine
argv[6]: -s
argv[7]: 31,lpc
argv[8]: -l
argv[9]: bootrom,/var/BHYVE_UEFI_2.80.fd
argv[10]: -l
argv[11]: com1,/dev/zconsole
argv[12]: -l
argv[13]: com2,socket,/tmp/vm.ttyb
argv[14]: -s
argv[15]: 0,hostbridge,model=i440fx
argv[16]: -c
argv[17]: 4
argv[18]: -m
argv[19]: 4096
argv[20]: -s
argv[21]: 0:4:0,virtio-blk,/dev/zvol/rdsk/zones/eceec5eb-22c7-e65b-fd6b-81ebdb36406b/disk0
argv[22]: -S
argv[23]: -s
argv[24]: 0:8:0,passthru,/dev/ppt1
argv[25]: -s
argv[26]: 0:4:1,nvme,/dev/zvol/rdsk/zones/eceec5eb-22c7-e65b-fd6b-81ebdb36406b/disk1
argv[27]: -s
argv[28]: 6:0,virtio-net-viona,net0
argv[29]: -c
argv[30]: sockets=1,cores=2,threads=2
argv[31]: -s
argv[32]: 30:0,fbuf,vga=off,unix=/tmp/vm.vnc
argv[33]: -s
argv[34]: 30:1,xhci,tablet
argv[35]: SYSbhyve-5
```
Removing the disk again:
```
[root@boron ~]# vmadm get eceec5eb-22c7-e65b-fd6b-81ebdb36406b | json disks
[
  {
    "path": "/dev/zvol/rdsk/zones/eceec5eb-22c7-e65b-fd6b-81ebdb36406b/disk0",
    "boot": true,
    "model": "virtio",
    "media": "disk",
    "pci_slot": "0:4:0",
    "uuid": "740e692f-1295-ed54-8fd0-97b823b04ccb",
    "zfs_filesystem": "zones/eceec5eb-22c7-e65b-fd6b-81ebdb36406b/disk0",
    "zpool": "zones",
    "size": 30720,
    "compression": "lz4",
    "refreservation": 31683,
    "block_size": 8192
  },
    {
      "path": "/dev/zvol/rdsk/zones/eceec5eb-22c7-e65b-fd6b-81ebdb36406b/disk1",
      "boot": false,
      "model": "nvme",
      "pci_slot": "0:4:1",
      "uuid": "abda4431-124b-cd8a-a943-efdce0f30475",
      "zfs_filesystem": "zones/eceec5eb-22c7-e65b-fd6b-81ebdb36406b/disk1",
      "zpool": "zones",
      "size": 1024,
      "compression": "off",
      "refreservation": 1058,
      "block_size": 8192
    }
]
[root@boron ~]# echo '{"remove_disks": ["/dev/zvol/rdsk/zones/eceec5eb-22c7-e65b-fd6b-81ebdb36406b/disk1"]}' | vmadm update eceec5eb-22c7-e65b-fd6b-81ebdb36406b
Successfully updated VM eceec5eb-22c7-e65b-fd6b-81ebdb36406b
[root@boron ~]# vmadm get eceec5eb-22c7-e65b-fd6b-81ebdb36406b | json disks
[
  {
    "path": "/dev/zvol/rdsk/zones/eceec5eb-22c7-e65b-fd6b-81ebdb36406b/disk0",
    "boot": true,
    "model": "virtio",
    "media": "disk",
    "pci_slot": "0:4:0",
    "uuid": "740e692f-1295-ed54-8fd0-97b823b04ccb",
    "zfs_filesystem": "zones/eceec5eb-22c7-e65b-fd6b-81ebdb36406b/disk0",
    "zpool": "zones",
    "size": 30720,
    "compression": "lz4",
    "refreservation": 31683,
    "block_size": 8192
  }
]
```

**Comment by sjorge** [comment]
Windows 10:
device manager
disk manager
disk manager - initialized

**Comment by sjorge** [comment]
illumos (OmniOS):

```
root@inflaton:~# prtconf -dD | grep nvme
        pcifb5d,a0a (pciexfb5d,a0a) [unknown vendor, unknown device] (driver name: nvme)
root@inflaton:~# prtconf
System Configuration:  Joyent  i86pc
Memory size: 2047 Megabytes
System Peripherals (Software Nodes):

i86pc
    scsi_vhci, instance #0
    pci, instance #0
        pci8086,1237 (driver not attached)
        pci1af4,2, instance #0
            blkdev, instance #0
        pcifb5d,a0a (driver not attached)
        pci1af4,1, instance #0
        isa, instance #0
            i8042, instance #0
                keyboard, instance #0
                mouse, instance #0
            asy, instance #0
            asy, instance #1 (driver not attached)
            pit_beep, instance #0 (driver not attached)
    fw, instance #0
        sb (driver not attached)
    used-resources (driver not attached)
    agpgart, instance #0 (driver not attached)
    options, instance #0
    pseudo, instance #0
    hv_vmbus, instance #0 (driver not attached)
    cpus, instance #0
        cpu (driver not attached)
        cpu (driver not attached)
        cpu (driver not attached)
        cpu (driver not attached)
        cpu (driver not attached)
        cpu (driver not attached)
        cpu (driver not attached)
        cpu (driver not attached)
```

The device is there, but illumos is not attaching.

**Comment by sjorge** [comment]
FreeBSD
```
root@fermion:~ # pciconf -lv
hostb0@pci0:0:0:0:      class=0x060000 card=0x00000000 chip=0x12378086 rev=0x00 hdr=0x00
    vendor     = 'Intel Corporation'
    device     = '440FX - 82441FX PMC [Natoma]'
    class      = bridge
    subclass   = HOST-PCI
nvme0@pci0:0:4:0:       class=0x010802 card=0x00000000 chip=0x0a0afb5d rev=0x00 hdr=0x00
    class      = mass storage
    subclass   = NVM
virtio_pci0@pci0:0:5:0: class=0x010000 card=0x00021af4 chip=0x10011af4 rev=0x00 hdr=0x00
    vendor     = 'Red Hat, Inc.'
    device     = 'Virtio block device'
    class      = mass storage
    subclass   = SCSI
virtio_pci1@pci0:0:6:0: class=0x020000 card=0x00011af4 chip=0x10001af4 rev=0x00 hdr=0x00
    vendor     = 'Red Hat, Inc.'
    device     = 'Virtio network device'
    class      = network
    subclass   = ethernet
isab0@pci0:0:31:0:      class=0x060100 card=0x00000000 chip=0x70008086 rev=0x00 hdr=0x00
    vendor     = 'Intel Corporation'
    device     = '82371SB PIIX3 ISA [Natoma/Triton II]'
    class      = bridge
    subclass   = PCI-ISA
```

```
root@fermion:~ # nvmecontrol devlist
 nvme0: bhyve-NVMe
    nvme0ns1 (1024MB)
root@fermion:~ # nvmecontrol identify nvme0
Controller Capabilities/Features
================================
Vendor ID:                   fb5d
Subsystem Vendor ID:         0000
Serial Number:               NVME-4-0
Model Number:                bhyve-NVMe
Firmware Version:            1.0
Recommended Arb Burst:       4
IEEE OUI Identifier:         58 9c fc
Multi-Path I/O Capabilities: Not Supported
Max Data Transfer Size:      2097152 bytes
Controller ID:               0x0000
Version:                     1.3.0

Admin Command Set Attributes
============================
Security Send/Receive:       Not Supported
Format NVM:                  Supported
Firmware Activate/Download:  Not Supported
Namespace Managment:         Not Supported
Device Self-test:            Not Supported
Directives:                  Not Supported
NVMe-MI Send/Receive:        Not Supported
Virtualization Management:   Not Supported
Doorbell Buffer Config:      Not Supported
Get LBA Status:              Not Supported
Sanitize:                    Not Supported
Abort Command Limit:         3
Async Event Request Limit:   5
Number of Firmware Slots:    N/A
Firmware Slot 1 Read-Only:   N/A
Per-Namespace SMART Log:     No
Error Log Page Entries:      1
Number of Power States:      2
Total NVM Capacity:          0 bytes
Unallocated NVM Capacity:    0 bytes

NVM Command Set Attributes
==========================
Submission Queue Entry Size
  Max:                       64
  Min:                       64
Completion Queue Entry Size
  Max:                       16
  Min:                       16
Number of Namespaces:        1
Compare Command:             Not Supported
Write Uncorrectable Command: Not Supported
Dataset Management Command:  Not Supported
Write Zeroes Command:        Not Supported
Save Features:               Not Supported
Reservations:                Not Supported
Timestamp feature:           Not Supported
Verify feature:              Not Supported
Fused Operation Support:     Not Supported
Format NVM Attributes:       All-NVM Erase, All-NVM Format
Volatile Write Cache:        Not Present

NVM Subsystem Name:
```

Looks like I need to create a name space before I can add a zpool on top, I have not figured out how to do this :( but it at least seems to be present and respond to the info commands.

**Comment by sjorge** [comment]
Oh no, I just remembered Andyf said that OmniOS shippes a different firmware for nvme...
I was still using the test firmware that was newer 👎 

**I redid all the tests and it's only working on windows with the firmware we ship :(**

I still think it's worth to have this though for once we update our bhyve firmware binaries, I'll push a new commit to smartos-live to make it clear in the man pages nvme is only working on windows for now.

**Comment by sjorge** [comment]
```
# ok
#
# /usr/vm/test/tests/test-zfs-limits.js TEST COMPLETE IN 10 SECONDS, SUMMARY:
#
# PASS: 9 / 9
#
#
#  TEST COMPLETE IN 2785 SECONDS, SUMMARY:
#
# PASS: 5154 / 5155
# FAIL: 1 / 5155
#
#  ** FAILED TESTS **
#  /usr/vm/test/tests/test-snapshots.js
#
# log files available in: /tmp/vmtest.1586549901.5118
#
```

Test also fails without my changes :(

https://pkg.blackdot.be/cores/vmtest.1586549901.5118.tar.bz2

**Comment by sjorge** [comment]
Running again with more ram for the vm, the snapshot tests succeed when run alone this way.
I'll upload the test results tomorrow as it takes way to long to run.

**Comment by sjorge** [comment]
```
# ok
#
# /usr/vm/test/tests/test-zfs-limits.js TEST COMPLETE IN 10 SECONDS, SUMMARY:
#
# PASS: 9 / 9
#
#
#  TEST COMPLETE IN 2619 SECONDS, SUMMARY:
#
# PASS: 5155 / 5155
#
# log files available in: /tmp/vmtest.1586553581.5112
#
```

Uploading results

**Comment by sjorge** [comment]
@papertigers @jasonbking ping

**Comment by sjorge** [comment]
I retested with both the shipped firmware and one from bexcran who is helming and effort to get the bhyve specific patches upstreamed to tianocore/ed2k.

| OS | smartos UEFI Firmware | bexcran UEFI firmware|
| ---| ------------------------- |---------------------- |
| Windows 10  | ✔️ | ✔️ |
| OmniOS | ❌ | ✔️ |
| FreeBSD | ❌ | ✔️ |

- boot PI with this and smartos-live change
- for vm in win10, omnios, freebsd vm
  - add a new disk with `"model": "nvme"`
  - boot vm
  - format nvme (extfat for win10, zfs for others)
  - write a random 128M file
  - halt vm
  - remove nvme disk

**Comment by sjorge** [comment]
Anything else that's needed for this? or is it good to go?

**Comment by sjorge** [comment]
@papertigers confirmed that this is working with linux too with our firmware, I'll update the man page in the other PR.

**Pull request merged**
