### PR TITLE
OS-8344 Fix LX post-14017

### PR DESCRIPTION
**Pull request by danmcd**

### CODE REVIEW

**Comment by bahamat** [comment]
For reference: https://www.illumos.org/issues/14017

**Review by bahamat — APPROVED** [review]
LGTM

**Comment by danmcd** [comment]
Thanks.  I'll update the ticket with testing when I get to it.  I believe a DTrace script will be sufficient.

**Review by papertigers — APPROVED** [review]

**Comment by danmcd** [comment]
Test results now in bug report.

**Comment by papertigers** [comment]
Thanks for the testing notes! 
IA set

**Pull request merged**
