### PR TITLE
OS-8196 Native zone support for link-local routes

### PR DESCRIPTION
**Pull request by hww3**
Hello- 

@mgerdts did an initial review of this change last year, and I have have been running this change on a number of SmartOS systems since that time. Details of the situation this aims to correct are described in #244.

I've specifically verified the following scenarios:

- no static routes (no errors)
- link-local routes in combination with a default route (no errors and link local route created first)
- ordering of non-link-local routes in combination with link-local routes (no errors and link-local route created before non-link-local route)

### CODE REVIEW

**Comment by jasonbking** [comment]
Everything there seems reasonable -- can you provide any testing notes?

**Comment by hww3** [comment]
Hi @jasonbking... of course, here's what I did to verify:

I have a few nodes at OVH that use "failover" ip addresses. These addresses are handed out on a CIDR subnet different than the admin network. The default route, however, is that of the default network. So a link-local route needs to be created before the default route. That's the rationale for this change.

I've been using this patch on 10-15 native zones across multiple hosts for the past year. These zones require the link local route to be created first as the default route is on the link-local network (that isn't the same as the IP address of the interface.) Without the patch, creating the default route fails with a "no route to host" error, but is successful with the patch.

I've also been running platform images with this fix on multiple systems that don't have static routes at all, and these all work as expected with the the patch.

I created a few (3 or 4) zones with a static (but not default) route in a lab setup. These all seemed to work just fine, in that the static routes were added as expected in the "non link-local" path.

I'm happy to provide any additional details you think would be helpful. Just let me know!

**Comment by danmcd** [comment]
Thank you for this.

**Comment by danmcd** [comment]
@hww3 -- I've noticed, BTW, that the normal `/etc/inet/static_routes` path in upstream illumos MIGHT benefit from some of this work.  Care to take a crack at it in illumos-gate?  I can help with integrating-to-gate's idiosyncracies.

**Comment by hww3** [comment]
Hi @danmcd-

I suspect you're right... I'll take a look and see if that part can be improved as well. I'll get in touch as I have questions about integrating!

**Pull request merged**
