### PR TITLE
Added MemAvailable to lx procfs. 

### PR DESCRIPTION
**Pull request by cneira**
MemAvailable /proc/mem entry is available since Linux Kernel +3.14.
Shell scripts could use this entry to determine the available memory for example https://github.com/GameServerManagers/LinuxGSM/blob/69ec2ecced43433dec2a96755f89ef98e0891b33/lgsm/functions/info_distro.sh

Signed-off-by: Carlos Neira <cneirabustos@gmail.com>

### CODE REVIEW

**Comment by jlevon** [comment]
This looks good @cneira - do you have any notes on testing you did? I gave this a quick run through on my system and it seems to work OK.

I filed OS-8145 internally for this

**Comment by cneira** [comment]
> This looks good @cneira - do you have any notes on testing you did? I gave this a quick run through on my system and it seems to work OK.
> 
> I filed OS-8145 internally for this

@jlevon, thanks for reviewing,
To test this I created an lx zone using image 04179d8e-188a-11e7-af4a-1349e98cbd17, 
then installed quake live as described in https://linuxgsm.com/lgsm/qlserver/,  then starting the  server using :

```bash
$ ./qlserver start
``` 
The script will complain that cannot parse /proc/MemAvailable on the old version, in this version will pass.

**Comment by jlevon** [comment]
Hi @jjelinek could you please look at IA for this?

**Comment by cneira** [comment]
thanks!

**Pull request merged**
