### PR TITLE
ASS: initial patches for SuSE Linux LX-Brandz support - version 0.1

### PR DESCRIPTION
**Pull request by plitc**

### CODE REVIEW

**Comment by jjelinek** [comment]
I filed OS-6326 for this. I'll review these changes and let you know if I have any concerns before we get these integrated.

**Comment by jjelinek** [comment]
I went through these changes and in general this is a good start. However, we cannot integrate the lx_boot_zone_suse.ksh as-is, since the handling for the networking is currently commented out. I am not familiar with SuSe but I looked through the test image you posted last week. However, it does not appear that the image has any systemd services for networking, or perhaps I just don't know what to look for.

The next step here is for us to get networking properly handling and integrated into the rest of the SmartOS zone bootup code so that networking will be configured correctly based on the vmadm setttings for the zone definitions.

There are probably some SuSE image customizations that will also be necessary to make sure things are properly hooked together. I'm happy to assist with getting all of this put together correctly so that we can add the SuSE support to the base platform.

**Comment by plitc** [comment]
I will commit all tests first here: https://github.com/plitc/illumos-joyent
finally, the final commits will again be in the ASS repository: https://github.com/ass-a2s/illumos-joyent/
and pull requests to https://github.com/joyent/illumos-joyent

i appreciate the support very much

**Comment by plitc** [comment]
for SuSE Linux LX-Brandz support: add network support https://github.com/plitc/illumos-joyent/commit/08c96cd49e9b6307a2c2895559eec0ea79f59c7a

**Comment by jjelinek** [comment]
Fixed with commit 8ff3cc1.

**Pull request closed without merging**
