### PR TITLE
joyent/illumos-joyent#232 Should LX forbid initial brk being at 0x0?

### PR DESCRIPTION
**Pull request by arekinath**
see also joyent/illumos-joyent#232

When we exec a shared lib in LX at the moment we leave brkbase set to 0x0. This is kind of a problem.

In the native brand when we exec a shared lib (as the comment in the code here explains), we get the userland linker to decide where to put the initial brkbase -- and it tells the kernel about the initial value by calling `brk()`. This means that we've kind of overloaded the semantics of `brk()` a little -- apart from its normal operation, in the specific case where we exec'd a shared lib and left `p_brkbase` as 0, calling `brk(0x1000)` means "set my initial brk to 0x1000 and don't change brksize", where in the normal situation that would mean "extend my brk to 0x1000 from wherever it is right now".

Linux does not share our overloaded semantics here, and to the Linux kernel `brk(0x1000)` always means the second semantic no matter what.

Now, when this code in `lx_brand.c` leaves `brkbase` set at `0x0` after execing a shared lib, on the next `brk()` call with a non-zero argument we're going to use the first semantic, but the linux binary assumes the second. So the Linux binary will do something like this:

```
brk(0) => 0    // check current brk
brk(11c0) => 11c0 // ok, our brk extends from 0x0 to 0x11c0 now
*(void *)(0x1000) => SEGFAULT // uh oh :(
```
We've basically told the Linux binary that it has a brk with a page in it, when we actually have not allocated it anything and just set `brkbase` to `11c0` while leaving `brksize` at `0`.

So we have to change this somehow. In this patch I've taken the easy way out and said "bugger it, just put it at PAGESIZE" when exec'ing a shared lib. We do this elsewhere in this code in similar situations. If we put it down there and something is in the way, then the first non-zero `brk()` call will just fail and return the brk at the same position, we won't map anything, and Linux binaries will fall back to using `mmap()` to back their `malloc()` rather than `brk()`. So, it seems like it should be fine.

Tested by hot-patching on the original machine that @teutat3s experienced the segfaults on (doesn't segfault after changing the `movq` to `0x1000` immediate). Also, in ubuntu-18.04 `/sbin/ldconfig.real` is now a shared lib that mallocs, which provides an easy test case for this (just run `ldconfig`). Tested with the latter on a DEBUG kernel built with this patch -- beforehand `ldconfig` segfaults, after it works fine.

### CODE REVIEW

**Comment by KodyKantor** [comment]
If it helps, I booted a system with this patch. I only have one LX zone, an Ubuntu 16.04, image_uuid: 7b5981c4-1889-11e7-b4c5-3f3bdfc9b88b

Everything seems fine to me.

**Comment by citrus-it** [comment]
I booted an OmniOS system with this patch and it fixes the segfaults that I usually see from `ldconfig`, LGTM.

**Comment by jlevon** [comment]
OS-8056

**Comment by jlevon** [comment]
So I went ahead and tested this on a whole bunch of LX images without problems/cores. I think this is good. @jjelinek - could you take care of merging this in maybe, as I reviewed?
The bug is:

OS-8056 lx brk should never start at zero

**Pull request merged**
