### PR TITLE
OS-8053 OS-8049 needs further fixes

### PR DESCRIPTION
**Pull request by jlevon**

### CODE REVIEW

**Comment by timfoster** [comment]
Should we be dropping the delivery of make from system-test-smartostest.mf now that we're pulling in all of the dmake package?

**Comment by jlevon** [comment]
> Should we be dropping the delivery of make from system-test-smartostest.mf now that we're pulling in all of the dmake package?

I had that there, got dropped accidentally.

**Comment by jlevon** [comment]
Testing notes added to ticket

**Comment by timfoster** [comment]
Thanks for the testing notes - lgtm

**Pull request merged**
