### PR TITLE
OS-8086 It's 2020

### PR DESCRIPTION
**Pull request by jjelinek**

### CODE REVIEW

**Comment by citrus-it** [comment]
Also usr/src/cmd/init/init.c for zone boot?

**Comment by jjelinek** [comment]
> Also usr/src/cmd/init/init.c for zone boot?

That's a good catch but we obviously haven't been maintaining that since it is currently showing 2012. I think that's because most people (nobody?) uses zlogin -C with SmartOS. However, I could update this too if you feel strongly.

**Comment by jjelinek** [comment]
> Think Andy's right, we could/should update init.c too
> 
> There's also the prototypes but that's an upstream thing. I can do that if you like.

OK, I'll update init.c here too. Since the prototypes come from upstream, I agree that we should do that in illumos-gate instead of here.

**Comment by sjorge** [comment]
@jjelinek I very sporadically use zlogin -C with a native zone, but you do not see the timestamp unless you attach pre-boot or during a reboot.

**Comment by jjelinek** [comment]
> @jjelinek I very sporadically use zlogin -C with a native zone, but you do not see the timestamp unless you attach pre-boot or during a reboot.

OK, thanks for letting me know. I updated the CR with the init change too now.

**Pull request merged**
