### PR TITLE
OS-8282 zfs_ioc_channel_program with hidden_args returns ZFS_ERR_IOC_ARG_UNAVAIL

### PR DESCRIPTION
**Pull request by arekinath**
see #362

### CODE REVIEW

**Comment by arekinath** [comment]
Testing done:
 * Built PI from this commit, booted it on an encrypted CN in a vmware VM, verified that `kbmadm activate` now works (where it didn't before)
 * Also hot-patched into some running real hardware CNs (by using `mdb -kw` to edit the `zfs_keys_channel_program` array and the length in the `zfs_ioc_vec` entry)

**Review by danmcd — APPROVED** [review]

**Comment by danmcd** [comment]
Soliciting another set of eyes for IA.  If none seen by bedtime today, US/Eastern, will IA it myself.

**Review by papertigers — APPROVED** [review]

**Comment by danmcd** [comment]
@papertigers mentioned to me on chat that:

usr/src/uts/common/fs/zfs/zfs_ioctl.c:  {"hidden_args", DATA_TYPE_NVLIST,       ZK_OPTIONAL},

Should your change mention it as DATA_TYPE_NVLIST as well?

**Comment by arekinath** [comment]
Hmm.. should `arg` be `DATA_TYPE_NVLIST` too, then?

**Comment by arekinath** [comment]
> `fnvpair_value_nvlist` will return NULL and we'll do a NULL deref in the ioc handler because we don't check it?

Thankfully it seems like `nvlist_add_common` saves us from this fate, if you give it a NULL nvlist it returns `EINVAL` and doesn't deref it

**Comment by danmcd** [comment]
Happy with testing, and because of that, I'm happy with vague typing for now.  IA-ing and pushing.

**Pull request merged**
