### PR TITLE
OS-8254 Remove lint from usr/src/uts

### PR DESCRIPTION
**Pull request by jasonbking**
This takes care of the SmartOS-specific bits in illumos-joyent to match what was done upstream to remove the vestiges of lint from usr/src/uts

### CODE REVIEW

**Comment by bahamat** [comment]
Does this get us closer to what's in gate?

**Comment by jasonbking** [comment]
No, it's unrelated to that. Basically the lint (and related) targets in makefiles are effectively dead targets that have not been used for some time (since all the illumos distributions switched to using smatch). Upstream removed these dead targets from illumos-gate. Since we have stuff that isn't upstream, we have dead targets that didn't get removed by the upstream work. This change basically does for those non-upstreamed bits what the upstream change did for illumos-gate -- remove the dead lint targets from usr/src/uts (and below).

**Comment by danmcd** [comment]
This is preemptive merge hell.

**Comment by danmcd** [comment]
Builds okay?  Can you do wsdiff?  These are IA questions, but thanks for doing this!

**Review by danmcd — APPROVED** [review]
Make sure you put testing notes in the ticket so someone can IA in good conscience.

**Comment by jasonbking** [comment]
Given _everything_ gets dumped into the proto area (all of illumos-extra, KVM, etc), is wsdiff output even possible/useful?

**Comment by jasonbking** [comment]
Just doing `gmake 0-illumos-stamp` with an otherwise empty `proto/` directory appears to just build illumos-joyent, so I was able to build this change using that (as well as build the current master -- twice to produce three proto areas -- two of master, one with the change), running wsdiff against them (master compared to master, and master compared to the lint removal branch) showed the same changes -- just buildstamp differences.

**Review by danmcd — APPROVED** [review]

**Pull request merged**
