### PR TITLE
/etc/zones/did.txt should be alternate-root aware

### PR DESCRIPTION
**Pull request by citrus-it**
This is something I found in OmniOS when writing a test-suite that makes use of `zone{adm,cfg} -R` to perform operations in an alternate root. It's probably not something that comes up in SmartOS but in the interest of code correctness, here's the fix.

Tested on OmniOS via ONU as follows:

```
#!/bin/ksh

rm -rf /tmp/aaa
mkdir -p /tmp/aaa/etc/zones
mkdir -p /tmp/aaa/var/run
cp /etc/zones/SUNW*.xml /tmp/aaa/etc/zones/
echo global:installed:/ > /tmp/aaa/etc/zones/index

sleep 1
cat /etc/zones/did.txt
zonecfg -R /tmp/aaa -z test1 'create -b; set zonepath=/tmp/aaa/test1; exit'
cat /etc/zones/did.txt
cat /tmp/aaa/etc/zones/did.txt

find /etc/zones -newer /tmp/aaa
```

Before, the global `/etc/zones/did.txt` is used to allocate the new ID.

```
bloody# ./did
21
22
cat: /tmp/aaa/etc/zones/did.txt: cannot open [No such file or directory]
/etc/zones/did.txt
```

After:

```
bloody# ./did
22
22
1
```

### CODE REVIEW

**Comment by sjorge** [comment]
Is there a reason why this can't go straight upstream? (or is it already?)

**Comment by citrus-it** [comment]
> Is there a reason why this can't go straight upstream? (or is it already?)

It's SmartOS/OmniOS specific, see

OS-200 need a better mechanism for storing persistent zone_did
https://smartos.org/bugview/OS-200

**Comment by sjorge** [comment]
Ah that makes sense then.

**Comment by jlevon** [comment]
I'll take a look if it's worth upstreaming?

**Comment by citrus-it** [comment]
> I'll take a look if it's worth upstreaming?

To gate? It came into OmniOS with some other zonecfg schema changes, I think as part of the lx work.
Some of that wad, in particular the `global-nic` stuff would probably be generally useful in gate but the consumer in OmniOS comes from the IPS/pkg(5) stuff at the moment.

**Comment by jlevon** [comment]
I took a look instead at upstreaming the debugid stuff:

https://github.com/jlevon/illumos-jlevon/tree/zone-did

It doesn't really look like a suitable upstreaming candidate for a few reasons:

 - the dtrace -x zone option doesn't seem to actually work: I still get probes in all zones
 - the debugid property is missing support in zonecfg info, export, etc.
 - it's of limited utility in general

**Comment by jlevon** [comment]
See OS-8166 for testing notes. Thanks Andy!

**Pull request merged**
